version: "3.9"

services:
  postgresql:
    container_name: postgresql
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/bitnami/postgresql/data
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USER}
      - POSTGRESQL_PASSWORD=${DATABASE_PASS}
      - POSTGRESQL_DATABASE=${DATABASE_NAME}